### ISSUE TITLE
Add lightweight HTML rendering

### ISSUE THREAD

**Issue by e-lo** [MobilityData/GTFS_Realtime_Best-Practices#11]
In order to increase navigability and legibility, add lightweight HTML rendering to this site at its GH Pages branch.

This can easily be accomplished using [mkdocs](https://www.mkdocs.org/) by adding a single config file and then using GitHub Actions to render it.

[Here is an example of the whole workflow. ](https://bluegenes.github.io/mkdocs-github-actions/)

**Comment by sccmcca** [comment]
As with #13, now resolved with gtfs.org: https://gtfs.org/realtime/best-practices/
