### ISSUE TITLE
Spec updates since first Best Practices draft

### ISSUE THREAD

**Issue by sccmcca** [MobilityData/GTFS_Realtime_Best-Practices#3]
There have been a number of updates to GTFS Realtime since the initial draft of the GTFS Realtime Best Practices (c. Oct 3, 2019). Here is a complete list of changes and Best Practice conflicts starting from the most recent entry as documented on the GTFS Realtime reference.md [commit history](https://github.com/google/transit/commits/master/gtfs-realtime/spec/en) :

**Feb 1, 2021**
-  Clarification of GTFS Realtime occupancy descriptions ([#259](https://github.com/google/transit/pull/259))
     - Changes:
          - Clarified wording and use of OccupancyStatus to reflect “states” of occupancies
          - Clarified wording and use occupancy_percentage to reflect “linear scale” occupancies
          - OccupancyStatus and occupancy_percentage are **experimental**
     - Conflicts:
          - Best Practices embedded in the spec
               - OccupancyStatus
                    - Consumers **should** represent OccupancyStatus values as the state indicated and intended by the producer.
               - occupancy_percentage
                    - The precision of occupancy_percentage **should** be low enough that individual passengers cannot be tracked boarding or alighting the vehicle.

**Nov 12, 2020**
- Proposal: Support stop assignments in GTFS-RT ([#219](https://github.com/google/transit/pull/219))
     - Changes:
          - **Added** StopTimeProperties in StopTimeUpdate for realtime stop assignments 
          - StopTimeProperties is **experimental**
     - Conflicts: 
          - Best Practices embedded in the spec
               - StopTimeUpdate.stop_id
                    - If StopTimeProperties.assigned_stop_id is populated, **it is preferred to** omit stop_id and use only stop_sequence.
               - StopTimePropoerties.assigned_stop_id
                    - The new assigned_stop_id **should not** result in a significantly different trip experience for the end user than the stop_id defined in GTFS stop_times.txt. In other words, the end user should not view this new stop_id as an "unusual change" if the new stop was presented within an app without any additional context.
                    - If this field is populated, StopTimeUpdate.stop_sequence must be populated and StopTimeUpdate.stop_id **should not** be populated.
                    - Stop assignments **should** be reflected in other GTFS-realtime fields as well (e.g., VehiclePosition.stop_id).
               - VehiclePosition.stop_id
                    - If StopTimeProperties.assigned_stop_id is used to assign a stop_id, this field **should** also reflect the change in stop_id.
                    
**Sep 10, 2020**
- Proposal: Support multi-car crowding in GTFS-RT ([#237](https://github.com/google/transit/pull/237))
     - Changes:
          - **Added** CarriageDetails to VehiclePosition for per-carriage occupancies
          - Carriage Details is **experimental**
     - Conflicts: 
          - Best Practices embedded in the spec
               - VehiclePosition.occupancy_status
                    - If multi_carriage_details is populated with per-carriage OccupancyStatus, then this field **should** describe the entire vehicle with all carriages accepting passengers considered.
               - VehiclePosition.occupancy_percentage
                    - If multi_carriage_details is populated with per-carriage occupancy_percentage, then this field **should** describe the entire vehicle with all carriages accepting passengers considered.
               - OccupancyStatus NOT_BOARDABLE
                    - **Useful** for special vehicles or carriages (engine, maintenance carriage, etc…).
               - CarriageDetails.id
                    - **Should** be unique per vehicle.

**Jul 29, 2020**
- Proposal: Support DUPLICATED trips in GTFS-RT ([#221](https://github.com/google/transit/pull/221)) 
     - Changes:
          - **Added** TripProperties to TripUpdate
          - Allows to duplicate trips and provide a new start_date and start_time
          - TripProperties is **experimental**
     - Conflicts: 
          - None
         
**Jul 23, 2020,**
- Proposal: Alert `tts_header_text`, `tts_description_text` no longer experimental ([#229](https://github.com/google/transit/pull/229))
     - Changes:
          - Made **official** `tts_header_text` and `tts_description_text`
     - Conflicts: 
          - Best Practices embedded in the spec
               - Alert.tts_header_text
                    - It **should** contain the same information as header_text but formatted such that it can read as text-to-speech (for example, abbreviations removed, numbers spelled out, etc.)
               - Alert.tts_description_text
                    - It **should** contain the same information as description_text but formatted such that it can be read as text-to-speech (for example, abbreviations removed, numbers spelled out, etc.)
                 
**Jul 20, 2020**
- fix: Fix a typo in occupancy_percentage description ([#234](https://github.com/google/transit/pull/234) )
     - Changes: 
          - Typo fix
     - Conflicts:
          - None

**Jul 15, 2020**
- feat: Label GTFS-RT ADDED trips as not fully specified ([#230](https://github.com/google/transit/pull/230))
     - Changes:
          - Added note that links to discussions about clarifying or deprecating ScheduleRelationship ADDED
     - Conflicts:
          - None 

**Apr 28, 2020**
- Mark severity level as final ([#214](https://github.com/google/transit/pull/214))
     - Changes:
          -  Made SeverityLevel **official**
     - Conflicts:
          - None
- Add occupancy_percentage ([#213](https://github.com/google/transit/pull/213))
     - Changes:
          -  **Added** occupancy_percentage as **experimental**
     - Conflicts:
          - Best Practices embedded in the spec
               - The precision of occupancy_percentage **should** be low enough that individual passengers cannot be tracked boarding or alighting the vehicle.

**Mar 20, 2020**
- Proposal: Recommend providing TripUpdate predictions for the next trip in block ([#206](https://github.com/google/transit/pull/206))
     - Changes:
          - Added **recommendation** for when a vehicle is serving multiple trips within the same block
     - Conflicts:
          - **Outdated** with current GTFS Realtime Best Practices for FeedEntity.trip_update:
               - When multiple trips in one block are included in one feed entity, their respective trip updates entities should be added to the feed entity in the same order that they are scheduled in the block (for more information about trips and blocks, please refer to GTFS trips.txt). For example, trips with trip_ids 1, 2, and 3 that all belong to one block, and the vehicle travels trip 1, then trip 2, and then trip 3, the trip_update entities should appear in the feed in the order of trip 1, then trip 2, and then trip 3. Trip 3's information and predictions should not occur in the feed prior to trip 2's or trip 1's.
          - Best Practices embedded in the spec
               - TripUpdate: the feed **should** include a TripUpdate for the trip currently being served by the vehicle. Producers are **encouraged** to include TripUpdates for one or more trips after the current trip in this vehicle's block if the producer is confident in the quality of the predictions for these future trip(s).

**Comment by barbeau** [comment]
These were reviewed and incorporated with PR https://github.com/MobilityData/GTFS_Realtime_Best-Practices/pull/1.
