### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by sccmcca** [MobilityData/GTFS_Realtime_Best-Practices#6]
Track semantic versioning of the GTFS Realtime Best Practices using GitHub release tags following [Semantic Versioning](https://semver.org/) conventions (vX.Y.Z).

Where X.Y.Z is the version name:
- X: Breaking changes
- Y: Added features
- Z: Editorial patches

Thoughts?

**Comment by barbeau** [comment]
Some kind of versioning makes sense to me. Would these be incremented on each pull request or could changes be batched?

**Comment by sccmcca** [comment]
Good question. With the proposed governance process in #7, I see no problem with batching changes. The effect of batching many changes may make the batch as a whole more political than individual changes, but the governance process would be there to regulate the outcome.

**Comment by barbeau** [comment]
The first release is now live using `v1.0` to match GTFS Schedule - https://github.com/MobilityData/GTFS_Realtime_Best-Practices/releases/tag/v1.0
